baseURL = "https://dividen.id"
title = "#dividen.id"
author = "Pribadi Pramudya"
languageCode = "en-US"
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
enableRobotsTXT = true

[permalinks]
  blog = "/:slug/"
  tags = "/blog/:slug"

[params]
  description = "Semua tentang srategi investasi dividen"
  title = "Strategi Investasi Dividen"
